"""empty message

Revision ID: 07b3d29e57e5
Revises: 8c2920e4dccb
Create Date: 2019-10-10 17:37:51.973471

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07b3d29e57e5'
down_revision = '8c2920e4dccb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sal_detail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sal_detail',
    sa.Column('comp_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('sal_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['comp_id'], ['company.id'], name='sal_detail_ibfk_1', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sal_id'], ['salary_sheet.id'], name='sal_detail_ibfk_2', ondelete='SET NULL'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
