"""empty message

Revision ID: 234797606d1c
Revises: 
Create Date: 2019-09-09 19:57:20.520502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '234797606d1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('employee', sa.Column('updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'updated')
    op.drop_column('employee', 'created')
    # ### end Alembic commands ###
