"""empty message

Revision ID: 796b0008c742
Revises: 88340775ded4
Create Date: 2019-09-30 15:09:41.062209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796b0008c742'
down_revision = '88340775ded4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advance', sa.Column('trans', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advance', 'trans')
    # ### end Alembic commands ###
