"""empty message

Revision ID: 7b7d37bcc1a3
Revises: 796b0008c742
Create Date: 2019-10-02 15:30:29.746331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b7d37bcc1a3'
down_revision = '796b0008c742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quick_input', sa.Column('feedback', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quick_input', 'feedback')
    # ### end Alembic commands ###
