"""empty message

Revision ID: 88340775ded4
Revises: ef872e725d2e
Create Date: 2019-09-20 13:17:49.473396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88340775ded4'
down_revision = 'ef872e725d2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendence', sa.Column('other_deduction', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendence', 'other_deduction')
    # ### end Alembic commands ###
