"""empty message

Revision ID: 8c2920e4dccb
Revises: 90580abd37d8
Create Date: 2019-10-08 13:12:20.347299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c2920e4dccb'
down_revision = '90580abd37d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('emp_id', 'employee', type_='unique')
    op.create_unique_constraint('emp_id', 'employee', ['name', 'dob', 'fathername', 'flag'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('emp_id', 'employee', type_='unique')
    op.create_unique_constraint('emp_id', 'employee', ['name', 'dob', 'fathername'])
    # ### end Alembic commands ###
