"""empty message

Revision ID: 90580abd37d8
Revises: 7b7d37bcc1a3
Create Date: 2019-10-03 14:29:01.097211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90580abd37d8'
down_revision = '7b7d37bcc1a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('flag', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'flag')
    # ### end Alembic commands ###
