"""empty message

Revision ID: a19e3a13ef87
Revises: b6527fe212cd
Create Date: 2019-11-01 13:21:09.507189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a19e3a13ef87'
down_revision = 'b6527fe212cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('photofile', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'photofile')
    # ### end Alembic commands ###
