"""empty message

Revision ID: b6527fe212cd
Revises: cedb75116033
Create Date: 2019-11-01 10:52:11.668004

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b6527fe212cd'
down_revision = 'cedb75116033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emp_curr_location')
    op.drop_table('emp_perm_location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emp_perm_location',
    sa.Column('emp_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('location_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['emp_id'], ['employee.id'], name='emp_perm_location_ibfk_1', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name='emp_perm_location_ibfk_2', ondelete='SET NULL'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('emp_curr_location',
    sa.Column('emp_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('location_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['emp_id'], ['employee.id'], name='emp_curr_location_ibfk_1', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name='emp_curr_location_ibfk_2', ondelete='SET NULL'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
