"""empty message

Revision ID: c7cbb3600459
Revises: cfc459dd0479
Create Date: 2019-10-29 19:28:48.171866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7cbb3600459'
down_revision = 'cfc459dd0479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_location', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_location', 'id')
    # ### end Alembic commands ###
