"""empty message

Revision ID: cfc459dd0479
Revises: 07b3d29e57e5
Create Date: 2019-10-10 17:38:17.192870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cfc459dd0479'
down_revision = '07b3d29e57e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salary_sheet_slips', 'days_payable')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salary_sheet_slips', sa.Column('days_payable', mysql.FLOAT(), nullable=False))
    # ### end Alembic commands ###
