"""empty message

Revision ID: ef872e725d2e
Revises: 234797606d1c
Create Date: 2019-09-10 11:24:29.741463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef872e725d2e'
down_revision = '234797606d1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('emp_id', 'employee', ['name', 'dob', 'fathername'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('emp_id', 'employee', type_='unique')
    # ### end Alembic commands ###
